  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '4001:4001'
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      - mongo
